# -*- coding: utf-8 -*-
"""hubconf_exercise.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1cB0fjvTQmQ3gfSgamoGoEf4ARNaRFv6_
"""

import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor, ToPILImage
from PIL import Image
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import torchmetrics
from torchmetrics import Precision, Recall, F1Score, Accuracy

from torchmetrics.classification import accuracy



transform_tensor_to_pil = ToPILImage()
transform_pil_to_tensor = ToTensor()

def load_data():

    # Download training data from open datasets.
    training_data = datasets.FashionMNIST(
        root="data",
        train=True,
        download=True,
        transform=ToTensor(),
    )

    # Download test data from open datasets.
    test_data = datasets.FashionMNIST(
        root="data",
        train=False,
        download=True,
        transform=ToTensor(),
    )
    return training_data, test_data


#mod_train_data = ModifiedDataset(training_data)
#mod_test_data = ModifiedDataset(test_data)


def create_dataloaders(training_data, test_data, batch_size=64):

    # Create data loaders.
    train_dataloader = DataLoader(training_data, batch_size=batch_size)
    test_dataloader = DataLoader(test_data, batch_size=batch_size)

    for X, y in test_dataloader:
        print(f"Shape of X [N, C, H, W]: {X.shape}")
        print(f"Shape of y: {y.shape} {y.dtype}")
        break
        
    return train_dataloader, test_dataloader

# print (len(np.unique([y for x,y in training_data])))

train_loader, test_loader = create_dataloaders(training_data, test_data, batch_size = 32)

class cs21d001(nn.Module):
    def __init__(self):
        super().__init__()
        self.m = nn.Softmax(dim =1)
        self.fc1 = nn.Linear(28*28*1, 120)
        self.fc2 = nn.Linear(120, 10)
# till now only structure built , pytorch doesn't know how to connect them using forward the connection will be establish
    def forward(self, x):
        x = torch.flatten(x, 1) # flatten all dimensions except batch
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        x = self.m(x)
        return x
# to see the class count using training set 
#print((len(np.unique([y for x,y in training_data]))))


#train the network
def train_network(train_loader, optimizer,criteria, e):
  for epoch in range(e):  # loop over the dataset multiple times

    running_loss = 0.0
    for i, data in enumerate(train_loader, 0):
        # get the inputs; data is a list of [inputs, labels]
        inputs, labels = data

        # zero the parameter gradients
        optimizer.zero_grad()# to avoid accumilation of the gradients 

        # forward + backward + optimize (3 imp steps)
        outputs = model(inputs)
        #print(outputs.shape, labels.shape)
        tmp = torch.nn.functional.one_hot(labels, num_classes= 10) # one hot encoding
        loss = criteria(outputs, tmp)
        loss.backward()# happens automatically by autograd
        optimizer.step() # optimize the parameters after backpropogation

        # print statistics
        running_loss += loss.item()# converts tensor of dim 1 to a python integer
        if i % 2000 == 1999:    # print every 2000 mini-batches
            print(f'[{epoch + 1}, {i + 1:5d}] loss: {running_loss / 2000:.3f}')
            running_loss = 0.0

  print('Finished Training')



#cross entropy
def loss_fun(y_pred, y_ground):
  v = -(y_ground * torch.log(y_pred + 0.0001))# to avoid 0 value some delta added
  v = torch.sum(v)
  return v


#write the get model
def get_model(train_loader,e = 10):
	model = cs21d001()
	optimizer = optim.SGD(model.parameters(), lr=0.001, momentum=0.9)
	criteria = loss_fun
	train_network(train_loader, optimizer,criteria,e)
	return model

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

def test(dataloader, model, loss_fn):
    size = len(dataloader.dataset) # total number of datapoints in the datatset (10000)
    num_batches = len(dataloader)# number of batches , batch sixze is 32 thus 313 batches
    model.eval()
    test_loss, correct = 0, 0
    with torch.no_grad():
        for X, y in dataloader:
            #X, y = X.to(device), y.to(device)
            tmp = torch.nn.functional.one_hot(y, num_classes= 10)# one hot encoding as the prediction vector is of dim(1,10)
            pred = model(X)
            test_loss += loss_fn(pred, tmp).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item() # ?
    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")
    accuracy1 = Accuracy()
    print('Accuracy :', accuracy1(pred,y))
    precision = Precision(average = 'macro', num_classes = 10)# macro for calculating score per class and then taking avaerage of it
    print('precision :', precision(pred,y))

    recall = Recall(average = 'macro', num_classes = 10) # Calculate the metric for each class separately, and average the metrics across classes 
    print('recall :', recall(pred,y))
    f1_score = F1Score(average = 'macro', num_classes = 10)
    print('f1_score :', f1_score(pred,y))
    return accuracy1, precision, recall, f1_score

test(test_loader, model, loss_fun)

def test_model(model1, test_data_loader):
	a,p,r,f1 = test(test_data_loader, model1, loss_fun)
	return a,p,r,f1
	
